spring:
  application:
    name: micro-weather-config-client
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/