server:
  port: 8888
spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lizhilin311/tauren-weather
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
